version: '3.8'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: pis
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    networks:
      - seller_net

volumes:
  mongo-data:

networks:
  seller_net:
    driver: bridge
    external: true