version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/usr/share/nginx/html:rw
    networks:
      - seller_net

networks:
  seller_net:
    driver: bridge
    external: true
