version: '3.8'

services:

  mongo:
    extends:
      file: docker-compose-mongo.yml
      service: mongo

  nginx:
    extends:
      file: docker-compose-nginx.yml
      service: nginx
  api:
    extends:
      file: docker-compose-api.yml
      service: api
    depends_on:
      - mongo
      - nginx

  # app:
  #   extends:
  #     file: docker-compose-app.yml
  #     service: app
  #   depends_on:
  #     - api

volumes:
  mongo-data:

networks:
  seller_net:
    driver: bridge
    external: true



