version: '3.8'

services:
  postgres:
    extends:
      file: docker-compose-postgres.yml
      service: postgres

  api:
    extends:
      file: docker-compose-api.yml
      service: api
    depends_on:
      - postgres

  app:
    extends:
      file: docker-compose-app.yml
      service: app
    depends_on:
      - api

volumes:
  postgres_data:
